version: '3.8'

services:
  app:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db        # Service name of the MySQL container
      DB_PORT: 3306      # MySQL container port
      DB_USER: root
      DB_PASSWORD: example

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33060:3306"   # Exposes MySQL to host machine if needed
